### ISSUE TITLE
Canary expired.

### ISSUE THREAD

**Issue by therealraven** [ViGrey/latchbox#4]
https://github.com/ViGrey/latchbox/blob/master/canary.txt

Says to expect update by 2018-07-01.

Is not updated.

**Comment by ViGrey** [comment]
My apologies.  Will update that shortly.  Got distracted by a lot of things.  Thank you for informing me.

**Comment by ViGrey** [comment]
Fixed.  Thanks again for informing me of this.

**Comment by therealraven** [comment]
> Expect an updated warrant canary by 2019-01-01T00:00:00+00:00

**Comment by ViGrey** [comment]
Dang it, I keep forgetting about it.  I'll update the canary after I get back from CypherCon, but I won't have time until then.
